import type { LazyConfig, SelectConfig } from './types';

export const DEFAULTS: SelectConfig = {
  options: [],
  source: '',
  lazy: {},
  multiple: false,
  searchable: false,
  placeholder: 'Select...',
  searchPlaceholder: 'Search...',
  positioning: 'dropdown',
  size: 'md',
  clearable: false,
  creatable: false,
  createLabel: 'Create "{value}"',
  disabled: false,
  maxItems: 0,
  maxHeight: 300,
  closeOnSelect: null,
  name: '',
  value: '',
  cssClass: '',
  flip: true,
  animationDuration: 150,
  zIndex: 9999,
  portalTo: null,
  emptyText: 'No options found',
  loadingText: 'Loading...',
  renderOption: null,
  renderSelected: null,
  renderTag: null,
  renderEmpty: null,
  onChange: null,
  onOpen: null,
  onClose: null,
  onSearch: null,
  onCreate: null,
};

export const LAZY_DEFAULTS: LazyConfig = {
  pageSize: 20,
  searchParam: 'q',
  pageParam: 'page',
  pageSizeParam: 'per_page',
  dataPath: 'data',
  totalPath: 'meta.total',
  lastPagePath: 'meta.last_page',
  headers: {},
  transformResponse: null,
  debounce: 300,
  loadOnInit: false,
};

export const CSS = {
  container: 'fs',
  open: 'fs--open',
  disabled: 'fs--disabled',
  hasValue: 'fs--has-value',
  trigger: 'fs__trigger',
  triggerLabel: 'fs__trigger-label',
  triggerLabelEmpty: 'fs__trigger-label--empty',
  triggerArrow: 'fs__trigger-arrow',
  triggerClear: 'fs__trigger-clear',
  dropdown: 'fs__dropdown',
  dropdownOpen: 'fs__dropdown--open',
  search: 'fs__search',
  searchInput: 'fs__search-input',
  list: 'fs__list',
  option: 'fs__option',
  optionSelected: 'fs__option--selected',
  optionHighlighted: 'fs__option--highlighted',
  optionDisabled: 'fs__option--disabled',
  optionCreate: 'fs__option--create',
  optionContent: 'fs__option-content',
  optionImage: 'fs__option-image',
  optionIcon: 'fs__option-icon',
  optionText: 'fs__option-text',
  optionLabel: 'fs__option-label',
  optionDesc: 'fs__option-desc',
  optionCheck: 'fs__option-check',
  group: 'fs__group',
  groupLabel: 'fs__group-label',
  tag: 'fs__tag',
  tagLabel: 'fs__tag-label',
  tagRemove: 'fs__tag-remove',
  status: 'fs__status',
  statusLoading: 'fs__status--loading',
  statusEmpty: 'fs__status--empty',
  separator: 'fs__separator',
  sentinel: 'fs__sentinel',
} as const;

export const ICONS = {
  arrow: `<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M3 4.5L6 7.5L9 4.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
  clear: `<svg width="12" height="12" viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M3 3L9 9M9 3L3 9" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>`,
  check: `<svg width="14" height="14" viewBox="0 0 14 14" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M3 7L6 10L11 4" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>`,
  removeTag: `<svg width="10" height="10" viewBox="0 0 10 10" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M2 2L8 8M8 2L2 8" stroke="currentColor" stroke-width="1.5" stroke-linecap="round"/></svg>`,
} as const;
